### ISSUE TITLE
Potential runaway timers

### ISSUE THREAD

**Issue by gu3st** [nicememe/OddshotConverter#1]
In this block of code in app.js (line 15 currently)

```
      youtube.refresh(function() {
         setInterval(fetch, 2000, 'OddshotBot'); // maximum 30 requests per minute https://github.com/reddit/reddit/wiki/API
         setInterval(youtube.refresh, 1800000); // YouTube access_token expires every 1 hour, refresh for a new token every 30 minutes.
         // TODO: Crontab might be more useful
      });
```

You're setting interval on youtube.refresh on the fetch function, however you're never clearing that setInterval call, which (looks like) will create an increasing number of timers that never get cleared

**Comment by domcx** [comment]
The timers are never created again (which is what i think you mean?). It appears to me like fetch happens every 2 seconds only, however the youtube.refresh function is called once every hour, to update the token as described. It appears like everything is in order, although this code is a tower of functions that is difficult to read, so I might be wrong.

**Comment by dank** [comment]
I'm not too sure if I need to close the setInterval because it's looping forever. I'll do more research and re-open if needed.

**Comment by gu3st** [comment]
Every time you're calling youtube.refresh, you're also setting another timer on fetch, but not clearing the past timer on it.

So after 3 hours, you will have 7 separate instances of fetch, running on a 2 second timer (The inital one, plus the newly started ones at .5h, 1h, 1.5h, 2h 2.5h and 3h.)

I hope this makes it make more sense as to the bug I'm pointing out.
