### ISSUE TITLE
Youtube link is broken to this github

### ISSUE THREAD

**Issue by HarrisJT** [nicememe/OddshotConverter#2]
It links to this: https://github.com/nicememe/oddshot not https://github.com/nicememe/OddshotConverter/

**Comment by dank** [comment]
https://github.com/nicememe/OddshotConverter/blob/master/app.js#L59-67
Clearly has the correct links, can you link me to the video that this happened in?

Thanks!

**Comment by HarrisJT** [comment]
On your main YouTube profile, github link in top right corner

**Comment by dank** [comment]
Thanks! I fixed it.
